@echo off
echo Stopping services...

net stop ALG
net stop AppIDSvc
net stop Appinfo
net stop AppReadiness
net stop AssignedAccessManagerSvc
net stop AudioEndpointBuilder
net stop AxInstSV
net stop BrokerInfrastructure
net stop camsvc
net stop CDPSvc
net stop CertPropSvc
net stop ClipSVC
net stop cloudidsvc
net stop CoreMessagingRegistrar
net stop CscService
net stop DcomLaunch
net stop DeviceAssociationService
net stop DeviceInstall
net stop DevQueryBroker
net stop diagnosticshub.standardcollector.service
net stop diagsvc
net stop DiagTrack
net stop DialogBlockingService
net stop DispBrokerDesktopSvc
net stop DisplayEnhancementService
net stop DmEnrollmentSvc
net stop dmwappushservice
net stop Dnscache
net stop DoSvc
net stop dot3svc
net stop DPS
net stop DsmSvc
net stop DsSvc
net stop Eaphost
net stop EFS
net stop embeddedmode
net stop EntAppSvc
net stop Fax
net stop fhsvc
net stop FontCache
net stop FrameServer
net stop GameInputSvc
net stop gpsvc
net stop HgClientService
net stop hidserv
net stop hns
net stop icssvc
net stop IKEEXT
net stop InstallService
net stop iphlpsvc
net stop IpxlatCfgSvc
net stop KtmRm
net stop lfsvc
net stop LicenseManager
net stop lltdsvc
net stop lmhosts
net stop LSM
net stop LxpSvc
net stop LxssManager
net stop MapsBroker
net stop McpManagementService
net stop MicrosoftEdgeElevationService
net stop MixedRealityOpenXRSvc
net stop mpssvc
net stop MSDTC
net stop MSiSCSI
net stop msiserver
net stop MsKeyboardFilter
net stop NaturalAuthentication
net stop NcaSvc
net stop NcbService
net stop NcdAutoSetup
net stop Netman
net stop netprofm
net stop NetSetupSvc
net stop NetTcpPortSharing
net stop NgcCtnrSvc
net stop NgcSvc
net stop nsi
net stop nvagent
net stop p2pimsvc
net stop p2psvc
net stop PcaSvc
net stop PeerDistSvc
net stop perceptionsimulation
net stop PhoneSvc
net stop pla
net stop PlugPlay
net stop PNRPAutoReg
net stop PNRPsvc
net stop PolicyAgent
net stop Power
net stop PrintNotify
net stop ProfSvc
net stop PushToInstall
net stop QWAVE
net stop RasAuto
net stop RasMan
net stop RemoteAccess
net stop RemoteRegistry
net stop RetailDemo
net stop RmSvc
net stop RpcEptMapper
net stop RpcLocator
net stop RpcSs
net stop SamSs
net stop SCardSvr
net stop ScDeviceEnum
net stop Schedule
net stop SCPolicySvc
net stop seclogon
net stop SecurityHealthService
net stop SEMgrSvc
net stop SENS
net stop Sense
net stop SensorDataService
net stop SensorService
net stop SensrSvc
net stop SessionEnv
net stop SgrmBroker
net stop SharedAccess
net stop SharedRealitySvc
net stop ShellHWDetection
net stop shpamsvc
net stop smphost
net stop SmsRouter
net stop SNMPTRAP
net stop spectrum
net stop Spooler
net stop sppsvc
net stop SSDPSRV
net stop ssh-agent
net stop SstpSvc
net stop StateRepository
net stop stisvc
net stop StorSvc
net stop svsvc
net stop swprv
net stop SystemEventsBroker
net stop TabletInputService
net stop TapiSrv
net stop TermService
net stop Themes
net stop TieringEngineService
net stop TimeBrokerSvc
net stop TokenBroker
net stop TrkWks
net stop TroubleshootingSvc
net stop tzautoupdate
net stop UevAgentService
net stop uhssvc
net stop UmRdpService
net stop upnphost
net stop UserManager
net stop UsoSvc
net stop VacSvc
net stop VaultSvc
net stop vds
net stop vmcompute
net stop vmicguestinterface
net stop vmicheartbeat
net stop vmickvpexchange
net stop vmicrdv
net stop vmicshutdown
net stop vmictimesync
net stop vmicvmsession
net stop vmicvss
net stop vmms
net stop VSS
net stop W32Time
net stop wbengine
net stop WbioSrvc
net stop Wcmsvc
net stop wcncsvc
net stop WdiServiceHost
net stop WdiSystemHost
net stop WdNisSvc
net stop WebClient
net stop Wecsvc
net stop WEPHOSTSVC
net stop wercplsupport
net stop WerSvc
net stop WFDSConMgrSvc
net stop WiaRpc
net stop WinDefend
net stop WinHttpAutoProxySvc
net stop WinRM
net stop wisvc
net stop WlanSvc
net stop wlidsvc
net stop wlpasvc
net stop WManSvc
net stop wmiApSrv
net stop WMPNetworkSvc
net stop workfolderssvc
net stop WpcMonSvc
net stop WPDBusEnum
net stop WpnService
net stop wscsvc
net stop WSearch
net stop WslInstaller
net stop WSLService
net stop wuauserv

echo All services stopped successfully.
pause
